name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code
    - run: dotnet build 
    - run: dotnet test
    - name: Builds the typescript code
      run: |
        npm install
        npm run build
      working-directory: ./DotnetTemplate.Web
    - name: Test TS 
      run: |
        npm run lint
        npm t
      working-directory: ./DotnetTemplate.Web

  publish:
    name: Publish to Dockerhub
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest 
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: rohanraj14/dotnet-app:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  publish-heroku:
    name: Publish to Heroku
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "dotnet-app07" #Must be unique in Heroku
          heroku_email: "rohan.raj14@gmail.com"
          usedocker: true